name: super_ticket_package
description: Elevate your Flutter apps with the Super Ticket Package—customizable, visually stunning event tickets for a modern user experience!
version: 0.0.4
homepage: https://github.com/NurhayatYurtaslan/super_ticket_package
documentation: https://github.com/NurhayatYurtaslan/super_ticket_package/blob/main/README.md

environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
